wallpaper {
    monitor = eDP-1
    path = /home/alday/Pictures/Wallpapers/persona3desk.jpg
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/alday/Pictures/Wallpapers/Botw.png
}

splash = false
#fully disable ipc
# ipc = off

